### ISSUE TITLE
Don't require node 19 if possible

### ISSUE THREAD

**Issue by mgiorgino-iobeya** [meza/jest-chance#194]
Some project can only use LTS versions of node, and node 20 is still not an active LTS version. Is node 19 really required to use `jest-chance` ?

**Comment by No-Cash-7970** [comment]
You can install tell npm or yarn to ignore the version and install anyway by adding the `--ignore-engine` flag. It may work with PNPM, but I haven't tried it.

NPM: `npm install -D jest-chance --ignore-engine`
Yarn: `yarn add -D jest-chance --ignore-engine`
